### ISSUE TITLE
Calcarea2 não abre corretamente

### ISSUE THREAD

**Issue by brunpz** [lmotta/calcarea2#1]
Ocorre esse erro:

Impossível carregar complemento 'calcarea2' Devido a um erro ao chamar o método Class Factory(). 

TypeError: QgisInterface missing 'mActionDigitizeWithCurve' action 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS 3.22.5/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/bruno/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\calcarea2\__init__.py", line 29, in classFactory
    return CalcAreaPlugin( iface )
  File "C:\Users/bruno/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\calcarea2\plugin.py", line 66, in __init__
    self.toolEvent = CalcAreaEvent( self.iface )
  File "C:\Users/bruno/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\calcarea2\calcareaevent.py", line 478, in __init__
    self.addFeatureEvent = AddFeatureEvent( iface )
  File "C:\Users/bruno/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\calcarea2\calcareaevent.py", line 213, in __init__
    self.geomPolygon = self.GeomPolygon( iface )
  File "C:\Users/bruno/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\calcarea2\calcareaevent.py", line 316, in __init__
    self.actionDigitizeWithCurve = getActionDigitizeWithCurve( iface )
  File "C:\Users/bruno/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\calcarea2\calcareaevent.py", line 308, in getActionDigitizeWithCurve
    raise TypeError(f"QgisInterface missing '{name}' action")
TypeError: QgisInterface missing 'mActionDigitizeWithCurve' action

Versão do Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versão do QGIS: 3.22.5-Białowieża Białowieża, c2723178 

Caminho do Python:
C:\Users/bruno/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geometric_attributes
C:/PROGRA~1/QGIS 3.22.5/apps/qgis-ltr/./python
C:/Users/bruno/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/bruno/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS 3.22.5/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.22.5\bin\python39.zip
C:\PROGRA~1\QGIS 3.22.5\apps\Python39\DLLs
C:\PROGRA~1\QGIS 3.22.5\apps\Python39\lib
C:\Program Files\QGIS 3.22.5\bin
C:\PROGRA~1\QGIS 3.22.5\apps\Python39
C:\PROGRA~1\QGIS 3.22.5\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS 3.22.5\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS 3.22.5\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS 3.22.5\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS 3.22.5\apps\Python39\lib\site-packages\Pythonwin
C:/Users/bruno/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\bruno\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
C:\Users\bruno\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms

**Comment by agiudiceandrea** [comment]
See https://github.com/lmotta/calcarea2/pull/6.

**Comment by janusbr-eng** [comment]
Bom dia! @lmotta não consegui instalar o plugin. Está aparecendo  o mesmo problema relatado pelo @brunpz. Gostaria muito de usar o plugin.

Erro Python : Impossível carregar complemento 'calcarea2' Devido a um erro ao chamar o método Class Factory(). Consulte o registro de mensagens (Erro Python) para mais detalhes.

2025-09-11T09:39:07     CRITICAL    Traceback (most recent call last):
              File "C:\PROGRA~1/QGIS32~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:\Users/bioim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\calcarea2\__init__.py", line 29, in classFactory
              return CalcAreaPlugin( iface )
              File "C:\Users/bioim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\calcarea2\plugin.py", line 66, in __init__
              self.toolEvent = CalcAreaEvent( self.iface )
              File "C:\Users/bioim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\calcarea2\calcareaevent.py", line 478, in __init__
              self.addFeatureEvent = AddFeatureEvent( iface )
              File "C:\Users/bioim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\calcarea2\calcareaevent.py", line 213, in __init__
              self.geomPolygon = self.GeomPolygon( iface )
              File "C:\Users/bioim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\calcarea2\calcareaevent.py", line 316, in __init__
              self.actionDigitizeWithCurve = getActionDigitizeWithCurve( iface )
              File "C:\Users/bioim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\calcarea2\calcareaevent.py", line 308, in getActionDigitizeWithCurve
              raise TypeError(f"QgisInterface missing '{name}' action")
             TypeError: QgisInterface missing 'mActionDigitizeWithCurve' action

**Comment by lmotta** [comment]
Bom dia,

Obrigado pelo interesse pelo meu trabalho.

Esse plugin foi feito numa versão do QGIS (4 anos atrás), depois, houve
mudança na biblioteca do QGIS, e não atualizei mais.

Para atualizar o plugin, é necessário fazer uma pesquisa na API atual do
QGIS, e verificar se é possível mostrar a área enquanto digitaliza.


Em qui., 11 de set. de 2025 às 09:55, janusbr-eng ***@***.***>
escreveu:

**Comment by agiudiceandrea** [comment]
@janusbr-eng, maybe the new plugin LiveMeasure https://plugins.qgis.org/plugins/LiveMeasure/ could be of some help.

**Comment by lmotta** [comment]
Thanks Andrea.

It is perfect!

Em qui., 11 de set. de 2025 às 13:33, Andrea Giudiceandrea <
***@***.***> escreveu:
