### ISSUE TITLE
Uncaught TypeError: QgisInterface missing 'mActionDigitizeWithCurve' action


### ISSUE THREAD

**Issue by baditaflorin** [lmotta/calcarea2#2]
Couldn't load plugin 'calcarea2' due to an error when calling its classFactory() method
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/user/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/calcarea2/__init__.py", line 29, in classFactory
    return CalcAreaPlugin( iface )
  File "/Users/user/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/calcarea2/plugin.py", line 66, in __init__
    self.toolEvent = CalcAreaEvent( self.iface )
  File "/Users/user/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/calcarea2/calcareaevent.py", line 478, in __init__
    self.addFeatureEvent = AddFeatureEvent( iface )
  File "/Users/user/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/calcarea2/calcareaevent.py", line 213, in __init__
    self.geomPolygon = self.GeomPolygon( iface )
  File "/Users/user/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/calcarea2/calcareaevent.py", line 316, in __init__
    self.actionDigitizeWithCurve = getActionDigitizeWithCurve( iface )
  File "/Users/user/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/calcarea2/calcareaevent.py", line 308, in getActionDigitizeWithCurve
    raise TypeError(f"QgisInterface missing '{name}' action")
TypeError: QgisInterface missing 'mActionDigitizeWithCurve' action

```
calcarea2 0.1, QGIS 3.24.1-Tisler on Darwin 21.4.0

**Comment by Supriyadi-ID** [comment]
same here with QGIS 3.22.13 LTR

**Comment by agiudiceandrea** [comment]
See https://github.com/lmotta/calcarea2/pull/6.
